name: Publish on crates.io
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          profile: minimal
          override: true
    - name: Cargo login
      uses: actions-rs/cargo@v1
      with:
        command: login
        args: -- ${{ secrets.CARGO_TOKEN }}
    - name: Publish transit_model
      uses: actions-rs/cargo@v1
      with:
        command: publish
        args: --all-features
